services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/lov-team/infinite-canvas:latest
    container_name: infinite-canvas
    ports: !override
      - "127.0.0.1:3009:3000"
    restart: unless-stopped
